### ISSUE TITLE
Windows paths don't seem to be parsed correctly

### ISSUE THREAD

**Issue by Snaptags** [danmarshall/indefinitely-typed#1]
I keep getting `error: this is not a node_modules folder.` messages.

This seems to be Windows-related, if I patch line 37 of `.\indefinitely-typed\dist\index.js` to explicitly add the folder, everything is working like a charm:
```
    var node_modules = path.resolve(cwd, packageJson.isScoped ? '../..' : '..') + "\\node_modules";
```

**Comment by danmarshall** [comment]
Hi @Snaptags , I'm also a Windows user. I think from the other issue you might not need to use this tool directly. I'm going to close this issue here and we can continue tracking in deckgl-typings.
